-- 조건
    -- 동일한 회원이 동일한 상품을 재구매한 데이터
-- 조회
    -- 재구매한 회원 ID와 재구매한 상품 ID
SELECT USER_ID, PRODUCT_ID FROM ONLINE_SALE 
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(USER_ID) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC